### ISSUE TITLE
Pre-release task list

### ISSUE THREAD

**Issue by tanelj** [Voog/design-amsterdam#2]
Bug list:
- [x] If article excerpt of the last article is missing then footer is on top of the article title
- [x] Allow to use side click to close language menu
- [x] Image margins are missing 
- [x] When example content (content-header) is empty then it should be hidden in preview mode
- [x] When the last element in content area is floating image and the next content are is gallery then they are together

![amsterdam-image-float](https://cloud.githubusercontent.com/assets/378755/3483259/2d0dce90-038c-11e4-838d-de71a7b7ee2a.png)
- [x] Line height should be smaller for long submenu
- [x] Long one word submenu is going over the border

![amsterdam-menu](https://cloud.githubusercontent.com/assets/378755/3483250/07de4ec4-038c-11e4-9364-ea3ad5627b04.png)
- [x] Very long word in common page content area is going over the border in FF (should be `word-break: break-all;` but there is  `word-break: break-word;`\- ok in Chrome)
- [x] Long word in comment is going over the border (should be `word-break: break-all;` but there is  `word-break: break-word;`)
- [x] Add more space before article comment header in mobile view

![amsterdam-article-comment](https://cloud.githubusercontent.com/assets/378755/3483248/f8cc41d4-038b-11e4-9b14-c1d6d2272804.png)
- [x] Add less space between articles in article listing in preview mode
- [x] Sticky header does not work in FF and IE
- [x] Sticky article headers are not working in FF and IE
- [x] In blog content only p-tag has margin (headings and text without wrapper have not margin)
- [x] Blog tags are missing
- [x] If the site header is short then language flag is too far
- [x] IE9: gives JS error `SCRIPT438: Object doesn't support property or method 'requestAnimationFrame'  main.min.js?1` 
- [x] IE9: input placeholders are missing
- [x] Article dates are not localized
